-- Nhớ người gửi và từng lượt sửa của người duyệt, xác nhận đã biết theo tài khoản.
-- Up Migration
ALTER TABLE works ADD COLUMN submitted_by bigint REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE work_items ADD COLUMN submitted_by bigint REFERENCES users(id) ON DELETE SET NULL;
CREATE TABLE approval_changes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_id bigint NOT NULL REFERENCES works(id) ON DELETE CASCADE,
  item_id bigint REFERENCES work_items(id) ON DELETE CASCADE,
  recipient_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  editor_id bigint REFERENCES users(id) ON DELETE SET NULL,
  entity_code text NOT NULL,
  entity_name text NOT NULL,
  changes jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(changes) = 'array'),
  approved_at timestamptz,
  acknowledged_at timestamptz
);
CREATE UNIQUE INDEX approval_changes_pending_work ON approval_changes(work_id)
  WHERE item_id IS NULL AND approved_at IS NULL;
CREATE UNIQUE INDEX approval_changes_pending_item ON approval_changes(item_id)
  WHERE item_id IS NOT NULL AND approved_at IS NULL;
CREATE INDEX approval_changes_unread ON approval_changes(recipient_id, work_id)
  WHERE approved_at IS NOT NULL AND acknowledged_at IS NULL;

CREATE OR REPLACE VIEW v_countable_works AS
  SELECT * FROM works
   WHERE approval_status NOT IN ('Chờ duyệt','Nháp');

CREATE OR REPLACE VIEW v_countable_items AS
  SELECT i.*
    FROM work_items i
    JOIN works w ON w.id = i.work_id
    LEFT JOIN work_items p ON p.id = i.parent_id
   WHERE i.approval_status NOT IN ('Chờ duyệt','Nháp')
     AND w.approval_status NOT IN ('Chờ duyệt','Nháp')
     AND (p.id IS NULL OR p.approval_status NOT IN ('Chờ duyệt','Nháp'));

-- Down Migration
DROP VIEW v_countable_items;
DROP VIEW v_countable_works;
DROP TABLE approval_changes;
ALTER TABLE work_items DROP COLUMN submitted_by;
ALTER TABLE works DROP COLUMN submitted_by;

CREATE OR REPLACE VIEW v_countable_works AS
  SELECT * FROM works
   WHERE approval_status NOT IN ('Chờ duyệt','Nháp');

CREATE OR REPLACE VIEW v_countable_items AS
  SELECT i.*
    FROM work_items i
    JOIN works w ON w.id = i.work_id
    LEFT JOIN work_items p ON p.id = i.parent_id
   WHERE i.approval_status NOT IN ('Chờ duyệt','Nháp')
     AND w.approval_status NOT IN ('Chờ duyệt','Nháp')
     AND (p.id IS NULL OR p.approval_status NOT IN ('Chờ duyệt','Nháp'));
